"""baseline: every table that predates real migrations

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-12

FROZEN_STATEMENTS below is a literal, historical snapshot of
src/api/services/patient_schema.py SCHEMA_STATEMENTS[0:92] as it stood
when this revision was written — NOT a live import of that list. This
migration used to `for statement in SCHEMA_STATEMENTS: op.execute(...)`,
importing the mutable current list directly; that meant 0001 silently
ran however many statements SCHEMA_STATEMENTS happened to contain on the
day it was applied, not the 92 the "baseline" name promised, and drifted
out of sync with 0002's own (also-broken) assumption about where the
baseline ended. Migrations must be frozen snapshots of what already
shipped — see migrations/patients_db/README.md's "Going forward" section
and tests/api/services/test_patient_schema_migrations.py, which fails
loudly the moment patient_schema.py grows a statement that isn't covered
by 0001+0002+0003 (or whatever the newest revision is), forcing a new
revision to be added deliberately instead of the boundary silently
drifting again.

Every statement is additive/idempotent (CREATE ... IF NOT EXISTS, ADD
COLUMN IF NOT EXISTS), so running this against a database that already
has some or all of these objects — true for every existing deployment,
since ensure_schema() already ran there — is a safe no-op beyond adding
the alembic_version row. On a genuinely empty database it builds the
schema from scratch.

downgrade() is intentionally a hard stop, not a DROP TABLE cascade: this
revision spans the platform's entire schema as it stood before real
migrations existed, so "downgrading" it would mean deleting every
patient's data. If you need to walk backward, restore from a database
backup taken before this revision was applied instead.
"""
from __future__ import annotations

from typing import List, Sequence, Union

from alembic import op

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FROZEN_STATEMENTS: List[str] = [
    '\n                CREATE TABLE IF NOT EXISTS patients (\n                    id UUID PRIMARY KEY,\n                    physician_id UUID NOT NULL,\n                    mrn TEXT,\n                    first_name TEXT NOT NULL,\n                    last_name TEXT NOT NULL,\n                    date_of_birth DATE,\n                    sex TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patients_physician_id_idx\n                    ON patients (physician_id);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS patient_diagnosis (\n                    id UUID PRIMARY KEY,\n                    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,\n                    cancer_site TEXT,\n                    histology TEXT,\n                    stage TEXT,\n                    tnm_t TEXT,\n                    tnm_n TEXT,\n                    tnm_m TEXT,\n                    diagnosis_date DATE,\n                    canonical_site_code TEXT,\n                    raw_text TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_diagnosis_patient_id_idx\n                    ON patient_diagnosis (patient_id);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS patient_biomarkers (\n                    id UUID PRIMARY KEY,\n                    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,\n                    biomarker_name TEXT NOT NULL,\n                    value TEXT,\n                    canonical_code TEXT,\n                    measured_date DATE,\n                    raw_text TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_biomarkers_patient_id_idx\n                    ON patient_biomarkers (patient_id);\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_biomarkers_name_idx\n                    ON patient_biomarkers (patient_id, biomarker_name);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS patient_treatment_history (\n                    id UUID PRIMARY KEY,\n                    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,\n                    treatment_type TEXT NOT NULL,\n                    regimen TEXT,\n                    line_of_therapy INTEGER,\n                    start_date DATE,\n                    end_date DATE,\n                    status TEXT,\n                    raw_text TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_treatment_history_patient_id_idx\n                    ON patient_treatment_history (patient_id);\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_treatment_history_timeline_idx\n                    ON patient_treatment_history (patient_id, start_date DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_timeline_events (\n                    id UUID PRIMARY KEY,\n                    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,\n                    event_type TEXT NOT NULL,\n                    event_date DATE,\n                    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,\n                    source TEXT NOT NULL DEFAULT 'manual',\n                    created_by UUID\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_timeline_events_patient_recorded_idx\n                    ON patient_timeline_events (patient_id, recorded_at DESC);\n                \n    ',
    "\n                ALTER TABLE patients ADD COLUMN IF NOT EXISTS user_id UUID;\n                ALTER TABLE patients ADD COLUMN IF NOT EXISTS invite_code TEXT;\n                ALTER TABLE patients ADD COLUMN IF NOT EXISTS invite_created_at TIMESTAMPTZ;\n                ALTER TABLE patients ADD COLUMN IF NOT EXISTS linked_at TIMESTAMPTZ;\n                ALTER TABLE patients\n                    ADD COLUMN IF NOT EXISTS link_status TEXT NOT NULL DEFAULT 'unlinked';\n                \n    ",
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS patients_user_id_uidx\n                    ON patients (user_id) WHERE user_id IS NOT NULL;\n                \n    ',
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS patients_invite_code_uidx\n                    ON patients (invite_code) WHERE invite_code IS NOT NULL;\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_link_requests (\n                    id UUID PRIMARY KEY,\n                    patient_user_id UUID NOT NULL,\n                    physician_id UUID NOT NULL,\n                    patient_first_name TEXT,\n                    patient_last_name TEXT,\n                    date_of_birth DATE,\n                    note TEXT,\n                    status TEXT NOT NULL DEFAULT 'pending',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    resolved_at TIMESTAMPTZ,\n                    resolved_by UUID,\n                    linked_patient_id UUID\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_link_requests_physician_idx\n                    ON patient_link_requests (physician_id, status, created_at DESC);\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_link_requests_user_idx\n                    ON patient_link_requests (patient_user_id, status);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS patient_conversations (\n                    id UUID PRIMARY KEY,\n                    patient_user_id UUID NOT NULL,\n                    patient_record_id UUID,\n                    title TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_conversations_user_idx\n                    ON patient_conversations (patient_user_id, updated_at DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_messages (\n                    id UUID PRIMARY KEY,\n                    conversation_id UUID NOT NULL\n                        REFERENCES patient_conversations(id) ON DELETE CASCADE,\n                    role TEXT NOT NULL,\n                    content TEXT NOT NULL,\n                    safety_category TEXT,\n                    sources JSONB NOT NULL DEFAULT '[]'::jsonb,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_messages_conversation_idx\n                    ON patient_messages (conversation_id, created_at);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_escalations (\n                    id UUID PRIMARY KEY,\n                    patient_user_id UUID NOT NULL,\n                    patient_record_id UUID,\n                    physician_id UUID NOT NULL,\n                    conversation_id UUID,\n                    question TEXT NOT NULL,\n                    ai_draft_answer TEXT,\n                    context_summary TEXT,\n                    urgency TEXT NOT NULL DEFAULT 'routine',\n                    status TEXT NOT NULL DEFAULT 'open',\n                    physician_response TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    answered_at TIMESTAMPTZ\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_escalations_physician_idx\n                    ON patient_escalations (physician_id, status, created_at DESC);\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_escalations_user_idx\n                    ON patient_escalations (patient_user_id, created_at DESC);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS patient_symptom_entries (\n                    id UUID PRIMARY KEY,\n                    patient_user_id UUID NOT NULL,\n                    patient_record_id UUID,\n                    symptom TEXT NOT NULL,\n                    severity SMALLINT,\n                    noted_on DATE NOT NULL DEFAULT CURRENT_DATE,\n                    note TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_symptom_entries_user_idx\n                    ON patient_symptom_entries (patient_user_id, noted_on DESC);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS patient_profiles (\n                    id UUID PRIMARY KEY,\n                    user_id UUID NOT NULL,\n                    first_name TEXT,\n                    last_name TEXT,\n                    date_of_birth DATE,\n                    sex TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS patient_profiles_user_id_uidx\n                    ON patient_profiles (user_id);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_care_team_links (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    physician_id UUID NOT NULL,\n                    role TEXT NOT NULL DEFAULT 'oncologist',\n                    legacy_patient_record_id UUID\n                        REFERENCES patients(id) ON DELETE SET NULL,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    is_primary BOOLEAN NOT NULL DEFAULT false,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_care_team_links_profile_idx\n                    ON patient_care_team_links (patient_profile_id, status);\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS patient_care_team_links_physician_idx\n                    ON patient_care_team_links (physician_id, status);\n                \n    ',
    "\n                CREATE UNIQUE INDEX IF NOT EXISTS patient_care_team_links_active_uidx\n                    ON patient_care_team_links (patient_profile_id, physician_id)\n                    WHERE status = 'active';\n                \n    ",
    "\n                CREATE TABLE IF NOT EXISTS patient_comorbidities (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    condition_name TEXT NOT NULL,\n                    canonical_code TEXT,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    onset_date DATE,\n                    resolved_date DATE,\n                    raw_text TEXT,\n                    source_type TEXT NOT NULL DEFAULT 'patient_manual',\n                    source_document_id UUID,\n                    verification_status TEXT NOT NULL DEFAULT 'extracted',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_comorbidities_profile_idx\n                    ON patient_comorbidities (patient_profile_id, status);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_allergies (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    allergen TEXT NOT NULL,\n                    reaction TEXT,\n                    severity TEXT,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    source_type TEXT NOT NULL DEFAULT 'patient_manual',\n                    source_document_id UUID,\n                    verification_status TEXT NOT NULL DEFAULT 'extracted',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_allergies_profile_idx\n                    ON patient_allergies (patient_profile_id, status);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_diagnoses (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    cancer_site TEXT,\n                    histology TEXT,\n                    stage TEXT,\n                    tnm_t TEXT,\n                    tnm_n TEXT,\n                    tnm_m TEXT,\n                    diagnosis_date DATE,\n                    canonical_site_code TEXT,\n                    raw_text TEXT,\n                    source_type TEXT NOT NULL DEFAULT 'patient_manual',\n                    source_document_id UUID,\n                    verification_status TEXT NOT NULL DEFAULT 'extracted',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_diagnoses_profile_idx\n                    ON patient_diagnoses (patient_profile_id, created_at DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_biomarker_results (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    biomarker_name TEXT NOT NULL,\n                    value TEXT,\n                    canonical_code TEXT,\n                    measured_date DATE,\n                    raw_text TEXT,\n                    source_type TEXT NOT NULL DEFAULT 'patient_manual',\n                    source_document_id UUID,\n                    verification_status TEXT NOT NULL DEFAULT 'extracted',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_biomarker_results_profile_idx\n                    ON patient_biomarker_results (patient_profile_id, biomarker_name);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS treatment_episodes (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    regimen TEXT,\n                    modality TEXT,\n                    intent TEXT,\n                    line_of_therapy INTEGER,\n                    start_date DATE,\n                    end_date DATE,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    raw_text TEXT,\n                    source_type TEXT NOT NULL DEFAULT 'patient_manual',\n                    source_document_id UUID,\n                    verification_status TEXT NOT NULL DEFAULT 'extracted',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS treatment_episodes_profile_idx\n                    ON treatment_episodes (patient_profile_id, start_date DESC NULLS LAST);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS treatment_cycles (\n                    id UUID PRIMARY KEY,\n                    treatment_episode_id UUID NOT NULL\n                        REFERENCES treatment_episodes(id) ON DELETE CASCADE,\n                    cycle_number INTEGER,\n                    cycle_date DATE,\n                    status TEXT NOT NULL DEFAULT 'completed',\n                    notes TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS treatment_cycles_episode_idx\n                    ON treatment_cycles (treatment_episode_id, cycle_number);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS treatment_agents (\n                    id UUID PRIMARY KEY,\n                    treatment_episode_id UUID NOT NULL\n                        REFERENCES treatment_episodes(id) ON DELETE CASCADE,\n                    agent_name TEXT NOT NULL,\n                    rxnorm_code TEXT,\n                    dose TEXT,\n                    route TEXT,\n                    schedule TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS treatment_agents_episode_idx\n                    ON treatment_agents (treatment_episode_id);\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS treatment_agents_name_idx\n                    ON treatment_agents (agent_name);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS medication_exposures (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    generic_name TEXT NOT NULL,\n                    brand_name TEXT,\n                    rxnorm_code TEXT,\n                    dose TEXT,\n                    route TEXT,\n                    frequency TEXT,\n                    indication TEXT,\n                    start_date DATE,\n                    end_date DATE,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    source_type TEXT NOT NULL DEFAULT 'patient_manual',\n                    source_document_id UUID,\n                    verification_status TEXT NOT NULL DEFAULT 'extracted',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS medication_exposures_profile_idx\n                    ON medication_exposures (patient_profile_id, status);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS lab_results (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    loinc_code TEXT,\n                    test_name TEXT NOT NULL,\n                    canonical_test_name TEXT,\n                    value_numeric DOUBLE PRECISION,\n                    value_text TEXT,\n                    unit TEXT,\n                    reference_low DOUBLE PRECISION,\n                    reference_high DOUBLE PRECISION,\n                    abnormal_flag TEXT,\n                    specimen_type TEXT,\n                    collected_at TIMESTAMPTZ,\n                    resulted_at TIMESTAMPTZ,\n                    source_type TEXT NOT NULL DEFAULT 'patient_upload',\n                    source_document_id UUID,\n                    verification_status TEXT NOT NULL DEFAULT 'extracted',\n                    extraction_confidence REAL,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS lab_results_profile_idx\n                    ON lab_results (patient_profile_id, collected_at DESC);\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS lab_results_test_trend_idx\n                    ON lab_results (patient_profile_id, canonical_test_name, collected_at DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_vitals (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    vital_type TEXT NOT NULL,\n                    value_numeric DOUBLE PRECISION,\n                    unit TEXT,\n                    measured_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    source_type TEXT NOT NULL DEFAULT 'patient_manual',\n                    source_document_id UUID,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_vitals_trend_idx\n                    ON patient_vitals (patient_profile_id, vital_type, measured_at DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS encounters (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    encounter_date DATE,\n                    encounter_type TEXT,\n                    provider_name TEXT,\n                    organization TEXT,\n                    patient_summary TEXT,\n                    clinician_note TEXT,\n                    structured_changes JSONB NOT NULL DEFAULT '{}'::jsonb,\n                    source_document_id UUID,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS encounters_profile_idx\n                    ON encounters (patient_profile_id, encounter_date DESC NULLS LAST);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_documents (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    document_type TEXT NOT NULL DEFAULT 'unclassified',\n                    filename TEXT,\n                    content_type TEXT,\n                    object_storage_uri TEXT,\n                    document_date DATE,\n                    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    extraction_status TEXT NOT NULL DEFAULT 'pending',\n                    parser_version TEXT,\n                    error_message TEXT\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_documents_profile_idx\n                    ON patient_documents (patient_profile_id, uploaded_at DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS document_extractions (\n                    id UUID PRIMARY KEY,\n                    document_id UUID NOT NULL\n                        REFERENCES patient_documents(id) ON DELETE CASCADE,\n                    extracted_fields JSONB NOT NULL DEFAULT '{}'::jsonb,\n                    extraction_confidence REAL,\n                    extraction_method TEXT,\n                    confirmed BOOLEAN NOT NULL DEFAULT false,\n                    confirmed_at TIMESTAMPTZ,\n                    confirmed_fields JSONB,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS document_extractions_document_idx\n                    ON document_extractions (document_id);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_state_snapshots (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    as_of TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    state JSONB NOT NULL,\n                    retrieval_features JSONB NOT NULL DEFAULT '{}'::jsonb,\n                    rule_version TEXT NOT NULL DEFAULT 'v1',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_state_snapshots_profile_idx\n                    ON patient_state_snapshots (patient_profile_id, created_at DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS patient_profile_timeline_events (\n                    id UUID PRIMARY KEY,\n                    patient_profile_id UUID NOT NULL\n                        REFERENCES patient_profiles(id) ON DELETE CASCADE,\n                    event_type TEXT NOT NULL,\n                    event_date DATE,\n                    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    payload JSONB NOT NULL DEFAULT '{}'::jsonb,\n                    source TEXT NOT NULL DEFAULT 'manual',\n                    created_by UUID\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS patient_profile_timeline_events_profile_idx\n                    ON patient_profile_timeline_events (patient_profile_id, recorded_at DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS evidence_sources (\n                    id UUID PRIMARY KEY,\n                    source_key TEXT NOT NULL,\n                    name TEXT NOT NULL,\n                    domain TEXT,\n                    authority_class TEXT NOT NULL DEFAULT 'B',\n                    authority_score REAL NOT NULL DEFAULT 0.5,\n                    source_type TEXT NOT NULL DEFAULT 'patient_education',\n                    allowed_intents JSONB NOT NULL DEFAULT '[]'::jsonb,\n                    patient_facing BOOLEAN NOT NULL DEFAULT true,\n                    ingestion_method TEXT NOT NULL DEFAULT 'manual',\n                    license_status TEXT NOT NULL DEFAULT 'unknown',\n                    active BOOLEAN NOT NULL DEFAULT true,\n                    last_verified_at TIMESTAMPTZ,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS evidence_sources_key_uidx\n                    ON evidence_sources (source_key);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS evidence_documents (\n                    id UUID PRIMARY KEY,\n                    source_id UUID NOT NULL REFERENCES evidence_sources(id) ON DELETE CASCADE,\n                    doc_id TEXT NOT NULL,\n                    title TEXT,\n                    url TEXT,\n                    qdrant_collection TEXT NOT NULL,\n                    applicability JSONB NOT NULL DEFAULT '{}'::jsonb,\n                    constraints JSONB NOT NULL DEFAULT '{}'::jsonb,\n                    last_ingested_at TIMESTAMPTZ,\n                    active BOOLEAN NOT NULL DEFAULT true,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS evidence_documents_source_idx\n                    ON evidence_documents (source_id);\n                \n    ',
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS evidence_documents_doc_id_uidx\n                    ON evidence_documents (doc_id);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS evidence_document_versions (\n                    id UUID PRIMARY KEY,\n                    evidence_document_id UUID NOT NULL\n                        REFERENCES evidence_documents(id) ON DELETE CASCADE,\n                    version_number INTEGER NOT NULL DEFAULT 1,\n                    content_hash TEXT,\n                    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    raw_text_excerpt TEXT\n                );\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS evidence_ingestion_runs (\n                    id UUID PRIMARY KEY,\n                    source_id UUID REFERENCES evidence_sources(id) ON DELETE SET NULL,\n                    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n                    finished_at TIMESTAMPTZ,\n                    status TEXT NOT NULL DEFAULT 'running',\n                    documents_ingested INTEGER NOT NULL DEFAULT 0,\n                    error_message TEXT\n                );\n                \n    ",
    '\n                CREATE TABLE IF NOT EXISTS evidence_chunk_registry (\n                    id UUID PRIMARY KEY,\n                    evidence_document_id UUID NOT NULL\n                        REFERENCES evidence_documents(id) ON DELETE CASCADE,\n                    qdrant_point_id TEXT NOT NULL,\n                    chunk_index INTEGER NOT NULL DEFAULT 0,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE INDEX IF NOT EXISTS evidence_chunk_registry_document_idx\n                    ON evidence_chunk_registry (evidence_document_id);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS community_profiles (\n                    id UUID PRIMARY KEY,\n                    user_id UUID NOT NULL,\n                    handle TEXT NOT NULL,\n                    avatar_key TEXT,\n                    tags JSONB NOT NULL DEFAULT '[]'::jsonb,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS community_profiles_user_uidx\n                    ON community_profiles (user_id);\n                \n    ',
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS community_profiles_handle_uidx\n                    ON community_profiles (handle);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS communities (\n                    id UUID PRIMARY KEY,\n                    slug TEXT NOT NULL,\n                    name TEXT NOT NULL,\n                    description TEXT,\n                    category TEXT,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS communities_slug_uidx\n                    ON communities (slug);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS community_memberships (\n                    id UUID PRIMARY KEY,\n                    community_id UUID NOT NULL REFERENCES communities(id) ON DELETE CASCADE,\n                    community_profile_id UUID NOT NULL\n                        REFERENCES community_profiles(id) ON DELETE CASCADE,\n                    joined_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS community_memberships_uidx\n                    ON community_memberships (community_id, community_profile_id);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS community_posts (\n                    id UUID PRIMARY KEY,\n                    community_id UUID NOT NULL REFERENCES communities(id) ON DELETE CASCADE,\n                    community_profile_id UUID NOT NULL\n                        REFERENCES community_profiles(id) ON DELETE CASCADE,\n                    title TEXT,\n                    body TEXT NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'visible',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS community_posts_community_idx\n                    ON community_posts (community_id, created_at DESC);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS community_comments (\n                    id UUID PRIMARY KEY,\n                    post_id UUID NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,\n                    community_profile_id UUID NOT NULL\n                        REFERENCES community_profiles(id) ON DELETE CASCADE,\n                    body TEXT NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'visible',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS community_comments_post_idx\n                    ON community_comments (post_id, created_at);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS community_reactions (\n                    id UUID PRIMARY KEY,\n                    target_type TEXT NOT NULL,\n                    target_id UUID NOT NULL,\n                    community_profile_id UUID NOT NULL\n                        REFERENCES community_profiles(id) ON DELETE CASCADE,\n                    reaction TEXT NOT NULL DEFAULT 'support',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS community_reactions_uidx\n                    ON community_reactions (target_type, target_id, community_profile_id);\n                \n    ',
    "\n                CREATE TABLE IF NOT EXISTS community_reports (\n                    id UUID PRIMARY KEY,\n                    target_type TEXT NOT NULL,\n                    target_id UUID NOT NULL,\n                    reported_by_profile_id UUID NOT NULL\n                        REFERENCES community_profiles(id) ON DELETE CASCADE,\n                    reason TEXT,\n                    status TEXT NOT NULL DEFAULT 'open',\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ",
    '\n                CREATE INDEX IF NOT EXISTS community_reports_status_idx\n                    ON community_reports (status, created_at DESC);\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS community_moderation_actions (\n                    id UUID PRIMARY KEY,\n                    target_type TEXT NOT NULL,\n                    target_id UUID NOT NULL,\n                    action TEXT NOT NULL,\n                    reason TEXT,\n                    acted_by UUID,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE TABLE IF NOT EXISTS community_blocked_users (\n                    id UUID PRIMARY KEY,\n                    blocker_profile_id UUID NOT NULL\n                        REFERENCES community_profiles(id) ON DELETE CASCADE,\n                    blocked_profile_id UUID NOT NULL\n                        REFERENCES community_profiles(id) ON DELETE CASCADE,\n                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n                );\n                \n    ',
    '\n                CREATE UNIQUE INDEX IF NOT EXISTS community_blocked_users_uidx\n                    ON community_blocked_users (blocker_profile_id, blocked_profile_id);\n\n    ',
]

def upgrade() -> None:
    for statement in FROZEN_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    raise RuntimeError(
        "0001_baseline cannot be downgraded — it spans the entire "
        "pre-migration schema for every patient. Restore from a backup "
        "taken before this revision was applied instead of downgrading."
    )
