"""
PDF report generation for Patient Matching, Treatment Comparison, and Query results.
Uses ReportLab for portable PDF output with comparison tables and analysis.
"""

from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image,
)


def _logo_path() -> Path:
    """Resolve path to the Paxis logo."""
    base = Path(__file__).resolve().parent.parent.parent.parent
    return base / "frontend" / "assets" / "paxis-logo.png"


def _logo_image():
    """Return ReportLab Image for the logo, or None if file not found. Preserves aspect ratio."""
    path = _logo_path()
    if path.exists():
        # paxis-logo.png is a wide wordmark (1094x352, ~3.1:1) — box sized to
        # roughly match so kind="proportional" doesn't render it tiny/thin.
        w, h = 1.1 * inch, 0.4 * inch  # preserves aspect ratio
        return Image(str(path), width=w, height=h, kind="proportional")
    return None


def _header_with_logo(story: list) -> None:
    """Prepend logo and divider to the story."""
    logo = _logo_image()
    if logo:
        story.append(logo)
        story.append(Spacer(1, 0.15 * inch))
    # Horizontal divider
    divider = Table([[""]], colWidths=[6.5 * inch])
    divider.setStyle(TableStyle([
        ("LINEABOVE", (0, 0), (-1, 0), 1, colors.HexColor("#d1d5db")),
    ]))
    story.append(divider)
    story.append(Spacer(1, 0.25 * inch))


def _style():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="ReportTitle",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="SectionHeader",
        parent=styles["Heading2"],
        fontSize=12,
        spaceAfter=8,
        spaceBefore=12,
    ))
    styles.add(ParagraphStyle(
        name="ReportMeta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#6b7280"),
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="TableCell",
        parent=styles["Normal"],
        fontSize=8,
        leading=10,
    ))
    styles.add(ParagraphStyle(
        name="TableCellHeader",
        parent=styles["TableCell"],
        fontName="Helvetica-Bold",
    ))
    return styles


def _cell(text: str, styles) -> Paragraph:
    """Wrap text in a Paragraph for table cell wrapping. Escapes XML special chars."""
    if text is None:
        text = "—"
    s = str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return Paragraph(s, styles["TableCell"])


def _cell_header(text: str, styles) -> Paragraph:
    """Wrap header text in a Paragraph for table header cells."""
    s = str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return Paragraph(s, styles["TableCellHeader"])


def _generated_by_text(data: Dict[str, Any]) -> str:
    """Return 'Report generated by [user]' or 'Generated: [date]' if no user."""
    user = data.get("generated_by") or data.get("user_name") or data.get("user_email")
    if user:
        return f"Report generated by {user}"
    return f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"


def _analysis_patient_match(data: Dict[str, Any]) -> str:
    n = data.get("total_matches", 0)
    summary = data.get("patient_summary", "Patient")
    if n == 0:
        return f"No matching studies were found for: {summary}. Consider broadening criteria or rephrasing the patient description."
    top = data.get("matches", [])[:3]
    strengths = [m.get("match_strength") for m in top if m.get("match_strength")]
    strong = sum(1 for s in strengths if s == "strong")
    return (
        f"For {summary}, {n} study(ies) were identified. "
        f"{strong} of the top results are strong matches. "
        "Review the comparison table for rationale, treatments, and key findings before considering trial eligibility."
    )


def _analysis_treatment_comparison(data: Dict[str, Any]) -> str:
    comp = data.get("comparison", {})
    a = comp.get("treatment_a_name", "Treatment A")
    b = comp.get("treatment_b_name", "Treatment B")
    summary = comp.get("comparison_summary", "")
    rec = comp.get("recommendation")
    out = f"Comparison of {a} versus {b}. {summary}"
    if rec:
        out += f" Recommendation: {rec}"
    else:
        out += " Use the comparison table and source evidence to inform clinical decisions."
    return out


def _analysis_query(data: Dict[str, Any]) -> str:
    n = len(data.get("retrieval_results") or [])
    q = (data.get("question") or "")[:80]
    return (
        f"Query: \"{q}\"... "
        f"Answer is supported by {n} retrieved source(s). "
        "Review the sources table for citations and evidence quality."
    )


def generate_patient_match_report(data: Dict[str, Any]) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, rightMargin=inch, leftMargin=inch, topMargin=inch, bottomMargin=inch)
    styles = _style()
    story = []

    _header_with_logo(story)
    story.append(Paragraph("Patient Matching Report", styles["ReportTitle"]))
    story.append(Paragraph(_generated_by_text(data), styles["ReportMeta"]))
    story.append(Spacer(1, 0.25 * inch))

    summary = data.get("patient_summary") or "—"
    story.append(Paragraph("Patient summary", styles["SectionHeader"]))
    story.append(Paragraph(summary, styles["Normal"]))
    story.append(Spacer(1, 0.2 * inch))

    profile = data.get("extracted_profile") or {}
    if profile:
        rows = [[_cell_header("Field", styles), _cell_header("Value", styles)]]
        for k, v in profile.items():
            if v is None:
                continue
            if isinstance(v, list):
                v = ", ".join(str(x) for x in v)
            rows.append([_cell(k.replace("_", " ").title(), styles), _cell(str(v), styles)])
        if len(rows) > 1:
            t = Table(rows, colWidths=[2 * inch, 4 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]))
            story.append(t)
            story.append(Spacer(1, 0.25 * inch))

    story.append(Paragraph("Analysis", styles["SectionHeader"]))
    story.append(Paragraph(_analysis_patient_match(data), styles["Normal"]))
    story.append(Spacer(1, 0.25 * inch))

    matches = data.get("matches") or []
    story.append(Paragraph("Comparison of matching studies", styles["SectionHeader"]))
    if not matches:
        story.append(Paragraph("No matching studies.", styles["Normal"]))
    else:
        rows = [[_cell_header("Title", styles), _cell_header("Author", styles), _cell_header("Year", styles),
                 _cell_header("Match %", styles), _cell_header("Strength", styles), _cell_header("Rationale", styles),
                 _cell_header("Treatment", styles), _cell_header("Key finding", styles)]]
        for m in matches:
            title = (m.get("title") or "—")
            author = (m.get("author") or "—")
            year = m.get("year") or "—"
            pct = f"{int((m.get('match_score') or 0) * 100)}%"
            strength = (m.get("match_strength") or "—").capitalize()
            rationale = (m.get("match_rationale") or "—")
            treatment = (m.get("treatment") or "—")
            key = (m.get("key_info") or "—")
            rows.append([_cell(title, styles), _cell(author, styles), _cell(str(year), styles), _cell(pct, styles),
                        _cell(strength, styles), _cell(rationale, styles), _cell(treatment, styles), _cell(key, styles)])
        t = Table(rows, colWidths=[1.2 * inch, 0.7 * inch, 0.4 * inch, 0.5 * inch, 0.55 * inch, 1.3 * inch, 1.0 * inch, 1.35 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ]))
        story.append(t)

    doc.build(story)
    return buf.getvalue()


def generate_treatment_comparison_report(data: Dict[str, Any]) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, rightMargin=inch, leftMargin=inch, topMargin=inch, bottomMargin=inch)
    styles = _style()
    story = []

    _header_with_logo(story)
    comp = data.get("comparison", {})
    a_name = comp.get("treatment_a_name", "Treatment A")
    b_name = comp.get("treatment_b_name", "Treatment B")

    story.append(Paragraph("Treatment Comparison Report", styles["ReportTitle"]))
    story.append(Paragraph(_generated_by_text(data), styles["ReportMeta"]))
    story.append(Spacer(1, 0.25 * inch))

    story.append(Paragraph("Comparison table", styles["SectionHeader"]))
    ev_a = comp.get("treatment_a_evidence") or {}
    ev_b = comp.get("treatment_b_evidence") or {}
    rows = [
        [_cell_header("Dimension", styles), _cell_header(a_name, styles), _cell_header(b_name, styles)],
        [_cell("Efficacy", styles), _cell(ev_a.get("efficacy") or "—", styles), _cell(ev_b.get("efficacy") or "—", styles)],
        [_cell("Safety", styles), _cell(ev_a.get("safety") or "—", styles), _cell(ev_b.get("safety") or "—", styles)],
        [_cell("Dosing", styles), _cell(ev_a.get("dosing") or "—", styles), _cell(ev_b.get("dosing") or "—", styles)],
        [_cell("Outcomes", styles), _cell(ev_a.get("outcomes") or "—", styles), _cell(ev_b.get("outcomes") or "—", styles)],
    ]
    t = Table(rows, colWidths=[1.2 * inch, 3.2 * inch, 3.2 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.25 * inch))

    story.append(Paragraph("Summary", styles["SectionHeader"]))
    story.append(Paragraph(comp.get("comparison_summary") or "No summary available.", styles["Normal"]))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Analysis", styles["SectionHeader"]))
    story.append(Paragraph(_analysis_treatment_comparison(data), styles["Normal"]))
    story.append(Spacer(1, 0.25 * inch))

    sources = data.get("sources") or []
    if sources:
        story.append(Paragraph("Source evidence", styles["SectionHeader"]))
        rows = [[_cell_header("Title", styles), _cell_header("Citation", styles), _cell_header("Year", styles), _cell_header("Excerpt", styles)]]
        for s in sources[:15]:
            title = s.get("title") or s.get("citation") or "—"
            citation = s.get("citation") or "—"
            year = s.get("year") or "—"
            content = s.get("content") or "—"
            rows.append([_cell(title, styles), _cell(citation, styles), _cell(str(year), styles), _cell(content, styles)])
        t = Table(rows, colWidths=[1.5 * inch, 1.5 * inch, 0.5 * inch, 3.2 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)

    doc.build(story)
    return buf.getvalue()


def generate_query_report(data: Dict[str, Any], format: str = "standard") -> bytes:
    """
    Generate a PDF report from a query result.
    format: "standard" | "patient_handout" | "clinic_note"
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, rightMargin=inch, leftMargin=inch, topMargin=inch, bottomMargin=inch)
    styles = _style()
    story = []

    question = data.get("question") or "—"
    short_answer = data.get("short_answer") or "—"
    justification = data.get("justification") or ""
    next_steps = data.get("next_steps") or []
    results = data.get("retrieval_results") or []

    _header_with_logo(story)
    if format == "patient_handout":
        story.append(Paragraph("Patient Information Sheet", styles["ReportTitle"]))
        story.append(Paragraph(_generated_by_text(data), styles["ReportMeta"]))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("This handout was prepared for you based on your discussion with your care team.", styles["Normal"]))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("What you need to know", styles["SectionHeader"]))
        story.append(Paragraph(short_answer, styles["Normal"]))
        if justification:
            story.append(Spacer(1, 0.15 * inch))
            story.append(Paragraph("Additional information", styles["SectionHeader"]))
            story.append(Paragraph(justification[:2000] + ("..." if len(justification) > 2000 else ""), styles["Normal"]))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("This information is based on published medical research. Please discuss any questions with your care team.", styles["Normal"]))
    elif format == "clinic_note":
        story.append(Paragraph("Clinic Note / Decision Aid", styles["ReportTitle"]))
        story.append(Paragraph(_generated_by_text(data), styles["ReportMeta"]))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("Clinical question", styles["SectionHeader"]))
        story.append(Paragraph(question, styles["Normal"]))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("Recommendation", styles["SectionHeader"]))
        story.append(Paragraph(short_answer, styles["Normal"]))
        if justification:
            story.append(Spacer(1, 0.15 * inch))
            story.append(Paragraph("Evidence summary", styles["SectionHeader"]))
            story.append(Paragraph(justification[:2000] + ("..." if len(justification) > 2000 else ""), styles["Normal"]))
        if next_steps:
            story.append(Spacer(1, 0.25 * inch))
            story.append(Paragraph("Next steps", styles["SectionHeader"]))
            steps_text = " • ".join(next_steps) if isinstance(next_steps, list) else str(next_steps)
            story.append(Paragraph(steps_text, styles["Normal"]))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("Sources", styles["SectionHeader"]))
        if not results:
            story.append(Paragraph("No sources.", styles["Normal"]))
        else:
            rows = [[_cell_header("Title", styles), _cell_header("Author", styles), _cell_header("Year", styles), _cell_header("Excerpt", styles)]]
            for r in results[:15]:
                title = r.get("title") or "—"
                author = r.get("author") or "—"
                year = r.get("year") or "—"
                content = r.get("content") or r.get("text") or "—"
                rows.append([_cell(title, styles), _cell(author, styles), _cell(str(year), styles), _cell(content, styles)])
            t = Table(rows, colWidths=[1.5 * inch, 1.0 * inch, 0.4 * inch, 3.6 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
            ]))
            story.append(t)
    else:
        # standard
        story.append(Paragraph("Query Report", styles["ReportTitle"]))
        story.append(Paragraph(_generated_by_text(data), styles["ReportMeta"]))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("Question", styles["SectionHeader"]))
        story.append(Paragraph(question, styles["Normal"]))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("Answer", styles["SectionHeader"]))
        story.append(Paragraph(short_answer, styles["Normal"]))
        if justification:
            story.append(Spacer(1, 0.15 * inch))
            story.append(Paragraph("Details", styles["SectionHeader"]))
            story.append(Paragraph(justification[:2000] + ("..." if len(justification) > 2000 else ""), styles["Normal"]))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("Analysis", styles["SectionHeader"]))
        story.append(Paragraph(_analysis_query(data), styles["Normal"]))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("Sources", styles["SectionHeader"]))
        if not results:
            story.append(Paragraph("No sources.", styles["Normal"]))
        else:
            rows = [[_cell_header("Title", styles), _cell_header("Author", styles), _cell_header("Year", styles),
                     _cell_header("Citation", styles), _cell_header("Excerpt", styles)]]
            for r in results[:20]:
                title = r.get("title") or "—"
                author = r.get("author") or "—"
                year = r.get("year") or "—"
                citation = r.get("citation") or "—"
                content = r.get("content") or r.get("text") or "—"
                rows.append([_cell(title, styles), _cell(author, styles), _cell(str(year), styles),
                             _cell(citation, styles), _cell(content, styles)])
            t = Table(rows, colWidths=[1.2 * inch, 1.0 * inch, 0.4 * inch, 1.2 * inch, 2.9 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
            ]))
            story.append(t)

    doc.build(story)
    return buf.getvalue()
